apiVersion: apps/v1
kind: Deployment
metadata:
  name: eaimos-api-deployment
  labels:
    app: eaimos-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eaimos-api
  template:
    metadata:
      labels:
        app: eaimos-api
    spec:
      containers:
      - name: api
        image: eaimos/api:latest
        ports:
        - containerPort: 8000
