"""
Agent Memory System Models
==========================
AgentMemory        — Key-value short/long-term memory for agent sessions
ConversationMemory — Summarized conversation history per agent session
OrganizationMemory — Shared organizational context (brand voice, guidelines)
"""
import enum
import uuid
from typing import Optional
from sqlalchemy import (
    ForeignKey, String, Text, Boolean, Integer,
    Enum, Index, JSON, Float
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from api.database.base import Base


class MemoryType(str, enum.Enum):
    SHORT_TERM = "SHORT_TERM"     # Session-scoped, cleared after session ends
    LONG_TERM = "LONG_TERM"       # Persisted across sessions, summarized
    EPISODIC = "EPISODIC"         # Specific past events / interactions
    SEMANTIC = "SEMANTIC"         # General knowledge / facts about the user/org


class AgentMemory(Base):
    """
    Agent memory item: a typed key-value pair scoped to an agent session or agent.
    Supports both session-level (ephemeral) and agent-level (persistent) memory.
    """
    __tablename__ = "agent_memories"
    __table_args__ = (
        Index("ix_agent_memories_agent_id", "agent_id"),
        Index("ix_agent_memories_session_id", "session_id"),
        Index("ix_agent_memories_org_id", "organization_id"),
        Index("ix_agent_memories_memory_type", "memory_type"),
    )

    agent_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_definitions.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Nullable — if null, memory is agent-level (long-term), not session-scoped
    session_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_sessions.id", ondelete="CASCADE"),
        nullable=True,
    )
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )

    memory_type: Mapped[MemoryType] = mapped_column(
        Enum(MemoryType), default=MemoryType.SHORT_TERM, nullable=False
    )
    memory_key: Mapped[str] = mapped_column(String(255), nullable=False)
    memory_value: Mapped[str] = mapped_column(Text, nullable=False)
    # Importance score for memory eviction policies (0.0 - 1.0)
    importance: Mapped[float] = mapped_column(Float, default=0.5, nullable=False)
    # Access count (for LRU eviction)
    access_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)


class ConversationMemory(Base):
    """
    Compressed/summarized memory of a conversation session.
    Generated by the LLM after every N turns to keep context manageable.
    """
    __tablename__ = "conversation_memories"
    __table_args__ = (
        Index("ix_conversation_memories_session_id", "session_id"),
        Index("ix_conversation_memories_org_id", "organization_id"),
    )

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    # LLM-generated summary of the conversation so far
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    # Number of turns this summary covers
    turns_covered: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    # Turn index at which this summary was generated
    summary_turn_index: Mapped[int] = mapped_column(Integer, default=0, nullable=False)


class OrganizationMemory(Base):
    """
    Shared organizational knowledge accessible by all agents in the org.
    Includes brand voice, tone guidelines, company facts, and user preferences.
    """
    __tablename__ = "organization_memories"
    __table_args__ = (
        Index("ix_organization_memories_org_id", "organization_id"),
        Index("ix_organization_memories_category", "category"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Category: "brand_voice", "company_facts", "audience", "guidelines", "preferences"
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    key: Mapped[str] = mapped_column(String(255), nullable=False)
    value: Mapped[str] = mapped_column(Text, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    # Extra structured metadata (JSON)
    meta_data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
