"""create_email_log_table

Revision ID: 532d3ff86c7a
Revises: fa551ae30a7c
Create Date: 2026-08-07 14:10:57.354478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '532d3ff86c7a'
down_revision: Union[str, None] = 'fa551ae30a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_logs_correlation_id', 'email_logs', ['correlation_id'], unique=False)
    op.create_index('idx_email_logs_created_at', 'email_logs', ['created_at'], unique=False)
    op.create_index('idx_email_logs_recipient', 'email_logs', ['recipient'], unique=False)
    op.create_index('idx_email_logs_status', 'email_logs', ['status'], unique=False)
    op.alter_column('organization_invitations', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='user_role_enum'),
               comment='Role to assign upon acceptance',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitations', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='user_role_enum'),
               comment=None,
               existing_comment='Role to assign upon acceptance',
               existing_nullable=False)
    op.drop_index('idx_email_logs_status', table_name='email_logs')
    op.drop_index('idx_email_logs_recipient', table_name='email_logs')
    op.drop_index('idx_email_logs_created_at', table_name='email_logs')
    op.drop_index('idx_email_logs_correlation_id', table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
