"""Add account deletion and other missing fields

Revision ID: fa551ae30a7c
Revises: 162bd0003e73
Create Date: 2026-08-06 16:44:12.106357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa551ae30a7c'
down_revision: Union[str, None] = '162bd0003e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def safe_alter_column_to_enum(table_name: str, column_name: str, enum_name: str, enum_type, default_val: str = None, nullable: bool = False):
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        if default_val:
            op.execute(sa.text(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} DROP DEFAULT"))
        op.execute(sa.text(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} TYPE {enum_name} USING {column_name}::text::{enum_name}"))
        if default_val:
            op.execute(sa.text(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} SET DEFAULT '{default_val}'::{enum_name}"))
        if not nullable:
            op.execute(sa.text(f"ALTER TABLE {table_name} ALTER COLUMN {column_name} SET NOT NULL"))
    else:
        op.alter_column(
            table_name, column_name,
            type_=enum_type,
            existing_nullable=nullable,
            existing_server_default=sa.text(f"'{default_val}'") if default_val else None
        )


def upgrade() -> None:
    # Pre-create custom PostgreSQL enum types if running against postgres
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        postgresql.ENUM('MARKETING', 'CONTENT', 'CAMPAIGN', 'CRM', 'ANALYTICS', 'RESEARCH', 'SEO', 'WORKFLOW', 'CUSTOM', 'SALES', 'SUPPORT', 'IMAGE', 'SOCIAL', name='agenttype').create(bind, checkfirst=True)
        postgresql.ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', name='agentstatus').create(bind, checkfirst=True)
        postgresql.ENUM('SHORT_TERM', 'LONG_TERM', 'EPISODIC', 'SEMANTIC', name='memorytype').create(bind, checkfirst=True)
        postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agentrunstatus').create(bind, checkfirst=True)
        postgresql.ENUM('SLACK', 'GOOGLE_DRIVE', 'GMAIL', 'GOOGLE_CALENDAR', 'HUBSPOT', 'SALESFORCE', 'WEBHOOK', 'CUSTOM_API', name='integrationprovider').create(bind, checkfirst=True)
        postgresql.ENUM('CONNECTED', 'DISCONNECTED', 'ERROR', 'PENDING_AUTH', name='integrationstatus').create(bind, checkfirst=True)
        postgresql.ENUM('IN_APP', 'EMAIL', 'SLACK', 'WEBHOOK', name='notificationchannel').create(bind, checkfirst=True)
        postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority').create(bind, checkfirst=True)
        postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='user_role_enum').create(bind, checkfirst=True)
        postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='workflowstatus').create(bind, checkfirst=True)
        postgresql.ENUM('MANUAL', 'SCHEDULED', 'WEBHOOK', 'CAMPAIGN_EVENT', 'CRM_EVENT', name='workflowtrigger').create(bind, checkfirst=True)
        postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'WAITING', name='executionstatus').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 of the raw token — plaintext NEVER stored'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='24 hours from creation'),
    sa.Column('is_used', sa.Boolean(), server_default='FALSE', nullable=False, comment='TRUE after successful verification'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP of the verification request'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('token_hash', name='uq_email_verification_token_hash')
    )
    op.create_index('idx_email_verification_expires_at', 'email_verification_tokens', ['expires_at'], unique=False)
    op.create_index('idx_email_verification_user_id', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index('idx_admin_action_logs_user', 'admin_action_logs', ['user_id'], unique=False)
    op.create_index('idx_agent_analytics_org', 'agent_analytics', ['organization_id'], unique=False)
    
    safe_alter_column_to_enum(
        'agent_definitions', 'agent_type', 'agenttype',
        sa.Enum('MARKETING', 'CONTENT', 'CAMPAIGN', 'CRM', 'ANALYTICS', 'RESEARCH', 'SEO', 'WORKFLOW', 'CUSTOM', 'SALES', 'SUPPORT', 'IMAGE', 'SOCIAL', name='agenttype'),
        default_val='CUSTOM', nullable=False
    )
    safe_alter_column_to_enum(
        'agent_definitions', 'status', 'agentstatus',
        sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='agentstatus'),
        default_val='ACTIVE', nullable=False
    )
    op.alter_column('agent_evaluations', 'updated_at',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                nullable=False)
    op.alter_column('agent_evaluations', 'version',
                existing_type=sa.INTEGER(),
                nullable=False,
                existing_server_default=sa.text('1'))
    op.create_index('idx_agent_kb_agent', 'agent_knowledge_bindings', ['agent_id'], unique=False)
    op.create_index('idx_agent_kb_collection', 'agent_knowledge_bindings', ['collection_id'], unique=False)
    
    safe_alter_column_to_enum(
        'agent_memories', 'memory_type', 'memorytype',
        sa.Enum('SHORT_TERM', 'LONG_TERM', 'EPISODIC', 'SEMANTIC', name='memorytype'),
        default_val='SHORT_TERM', nullable=False
    )
    safe_alter_column_to_enum(
        'agent_runs', 'status', 'agentrunstatus',
        sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agentrunstatus'),
        default_val='PENDING', nullable=False
    )
    op.create_index('idx_agent_tool_exec_org', 'agent_tool_executions', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_agent_tool_exec_run', 'agent_tool_executions', ['run_id'], unique=False)
    op.create_index('idx_agent_tools_org', 'agent_tools', ['organization_id'], unique=False)
    op.create_index('idx_agent_tools_type', 'agent_tools', ['tool_type'], unique=False)
    op.add_column('ai_image_collections', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ai_image_collections', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_image_collections', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('ai_image_collections', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('ai_image_collections', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.drop_index(op.f('ix_image_library_campaign_id'), table_name='ai_image_library')
    op.drop_index(op.f('ix_image_library_created_at'), table_name='ai_image_library')
    op.drop_index(op.f('ix_image_library_org_id'), table_name='ai_image_library')
    op.drop_index(op.f('ix_image_library_parent_id'), table_name='ai_image_library')
    op.drop_index(op.f('ix_image_library_run_id'), table_name='ai_image_library')
    op.drop_index(op.f('ix_image_library_user_id'), table_name='ai_image_library')
    op.add_column('ai_models', sa.Column('supports_images', sa.Boolean(), nullable=False))
    op.add_column('ai_providers', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('ai_token_usages', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('ai_token_usages', sa.Column('capability', sa.String(length=50), nullable=True))
    op.add_column('ai_token_usages', sa.Column('agent', sa.String(length=100), nullable=True))
    op.add_column('ai_token_usages', sa.Column('request_id', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_ai_token_usages_created_at'), table_name='ai_token_usages')
    op.drop_index(op.f('ix_ai_token_usages_organization_id'), table_name='ai_token_usages')
    op.drop_index(op.f('ix_ai_token_usages_user_id'), table_name='ai_token_usages')
    op.create_index('idx_cohorts_org', 'analytics_cohorts', ['organization_id'], unique=False)
    op.create_index('idx_analytics_dashboards_org', 'analytics_dashboards', ['organization_id'], unique=False)
    op.create_index('idx_analytics_events_org_type', 'analytics_events', ['organization_id', 'event_type', 'created_at'], unique=False)
    op.create_index('idx_funnel_steps_funnel', 'analytics_funnel_steps', ['funnel_id'], unique=False)
    op.create_index('idx_funnels_org', 'analytics_funnels', ['organization_id'], unique=False)
    op.create_index('idx_report_runs_org', 'analytics_report_runs', ['organization_id'], unique=False)
    op.create_index('idx_report_runs_report', 'analytics_report_runs', ['report_id'], unique=False)
    op.create_index('idx_analytics_reports_org', 'analytics_reports', ['organization_id'], unique=False)
    op.create_index('idx_snapshots_module', 'analytics_snapshots', ['organization_id', 'module'], unique=False)
    op.create_index('idx_snapshots_org_metric_period', 'analytics_snapshots', ['organization_id', 'metric_name', 'period', 'period_start'], unique=False)
    op.create_index('idx_analytics_widgets_dash', 'analytics_widgets', ['dashboard_id'], unique=False)
    op.create_index('idx_api_keys_active', 'api_keys', ['organization_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_api_keys_org_id', 'api_keys', ['organization_id'], unique=False)
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='CREATED | UPDATED | DELETED | ACCESSED | EXPORTED | RESTORED | PURGED',
               existing_nullable=False)
    op.create_index('idx_billing_alerts_org_id', 'billing_alerts', ['organization_id'], unique=False)
    op.create_index('idx_billing_plans_is_active', 'billing_plans', ['is_active'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('idx_billing_plans_tier', 'billing_plans', ['tier'], unique=False)
    op.create_index('idx_campaign_audiences_org', 'campaign_audiences', ['organization_id'], unique=False)
    op.create_index('idx_campaign_audiences_type', 'campaign_audiences', ['segment_type'], unique=False)
    op.create_index('idx_campaign_events_contact', 'campaign_events', ['contact_id'], unique=False)
    op.create_index('idx_campaign_events_created', 'campaign_events', ['created_at'], unique=False)
    op.create_index('idx_campaign_events_org_camp', 'campaign_events', ['organization_id', 'campaign_id'], unique=False)
    op.create_index('idx_campaign_events_type', 'campaign_events', ['event_type'], unique=False)
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_companies_organization_id'), table_name='companies')
    op.create_index('idx_assessments_org', 'compliance_assessments', ['organization_id'], unique=False)
    op.create_index('idx_custom_fields_org', 'contact_custom_fields', ['organization_id'], unique=False)
    op.create_index('idx_custom_values_contact', 'contact_custom_values', ['contact_id'], unique=False)
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index('ix_conversation_memories_org_id', 'conversation_memories', ['organization_id'], unique=False)
    op.create_index('idx_credit_tx_org_created', 'credit_transactions', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_credit_tx_reference', 'credit_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_credit_tx_type', 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index('idx_classification_rules_org', 'data_classification_rules', ['organization_id'], unique=False)
    op.create_index('idx_deal_stages_pipeline', 'deal_stages', ['pipeline_id'], unique=False)
    op.create_index('idx_deals_company', 'deals', ['company_id'], unique=False)
    op.create_index('idx_deals_contact', 'deals', ['contact_id'], unique=False)
    op.create_index('idx_deals_org', 'deals', ['organization_id'], unique=False)
    op.create_index('idx_deals_owner', 'deals', ['owner_id'], unique=False)
    op.create_index('idx_deals_pipeline_stage', 'deals', ['pipeline_id', 'stage_id'], unique=False)
    op.create_index('idx_embeddings_chunk_id', 'document_chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index('idx_embeddings_org_model', 'document_chunk_embeddings', ['organization_id', 'embedding_model'], unique=False)
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.create_index('idx_email_sends_contact', 'email_sends', ['contact_id'], unique=False)
    op.create_index('idx_email_sends_org_camp', 'email_sends', ['organization_id', 'campaign_id'], unique=False)
    op.create_index('idx_email_sends_status', 'email_sends', ['status'], unique=False)
    op.create_index('idx_email_subs_org_email', 'email_subscriptions', ['organization_id', 'email'], unique=False)
    op.create_index('idx_impersonation_logs_admin', 'impersonation_logs', ['admin_user_id'], unique=False)
    op.create_index('idx_impersonation_logs_user', 'impersonation_logs', ['impersonated_user_id'], unique=False)
    op.create_index('idx_sync_logs_org', 'integration_sync_logs', ['organization_id', 'created_at'], unique=False)
    safe_alter_column_to_enum(
        'integrations', 'provider', 'integrationprovider',
        sa.Enum('SLACK', 'GOOGLE_DRIVE', 'GMAIL', 'GOOGLE_CALENDAR', 'HUBSPOT', 'SALESFORCE', 'WEBHOOK', 'CUSTOM_API', name='integrationprovider'),
        default_val=None, nullable=False
    )
    safe_alter_column_to_enum(
        'integrations', 'status', 'integrationstatus',
        sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'PENDING_AUTH', name='integrationstatus'),
        default_val='PENDING_AUTH', nullable=False
    )
    op.create_index('idx_invoice_line_items_invoice_id', 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index('idx_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('idx_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('idx_invoices_org_id', 'invoices', ['organization_id'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoices_subscription_id', 'invoices', ['subscription_id'], unique=False)
    op.create_index('idx_ip_allowlists_org', 'ip_allowlists', ['organization_id'], unique=False)
    op.create_index('idx_knowledge_retrieval_org', 'knowledge_retrieval_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_knowledge_retrieval_user', 'knowledge_retrieval_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.create_index('idx_maintenance_windows_start', 'maintenance_windows', ['scheduled_start'], unique=False)
    op.create_index('idx_notification_batches_org', 'notification_batches', ['organization_id'], unique=False)
    op.create_index('idx_notification_deliv_org', 'notification_deliveries', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_notification_deliv_user', 'notification_deliveries', ['user_id'], unique=False)
    op.create_index('idx_notification_digests_user', 'notification_digests', ['user_id'], unique=False)
    
    safe_alter_column_to_enum(
        'notification_preferences', 'channel', 'notificationchannel',
        sa.Enum('IN_APP', 'EMAIL', 'SLACK', 'WEBHOOK', name='notificationchannel'),
        default_val=None, nullable=False
    )
    op.create_index('idx_notification_templates_org', 'notification_templates', ['organization_id'], unique=False)
    
    safe_alter_column_to_enum(
        'notifications', 'channel', 'notificationchannel',
        sa.Enum('IN_APP', 'EMAIL', 'SLACK', 'WEBHOOK', name='notificationchannel'),
        default_val='IN_APP', nullable=False
    )
    safe_alter_column_to_enum(
        'notifications', 'priority', 'notificationpriority',
        sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'),
        default_val='MEDIUM', nullable=False
    )
    op.create_index('idx_oauth_accounts_provider', 'oauth_accounts', ['provider'], unique=False)
    op.create_index('idx_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.create_index('idx_oauth_providers_org_id', 'oauth_providers', ['organization_id'], unique=False)
    op.create_index('idx_oauth_providers_provider', 'oauth_providers', ['provider'], unique=False)
    op.add_column('organization_invitations', sa.Column('resent_count', sa.Integer(), server_default='0', nullable=False, comment='Number of times the invitation email was resent'))
    op.add_column('organization_invitations', sa.Column('last_resent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_invitations', sa.Column('revoked_by', sa.UUID(), nullable=True, comment='User who revoked this invitation'))
    op.add_column('organization_invitations', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('organization_invitations', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Invitee email address',
               existing_nullable=False)
    safe_alter_column_to_enum(
        'organization_invitations', 'role', 'user_role_enum',
        sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='user_role_enum'),
        default_val=None, nullable=False
    )
    op.alter_column('organization_invitations', 'token',
               existing_type=sa.VARCHAR(length=128),
               comment='Secure random token (128-bit entropy, URL-safe base64)',
               existing_nullable=False)
    op.alter_column('organization_invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Invitation expires at this time (default: 72h from creation)',
               existing_nullable=False)
    op.create_foreign_key(None, 'organization_invitations', 'users', ['revoked_by'], ['id'], ondelete='SET NULL')
    op.create_index('idx_org_settings_org_key', 'organization_settings', ['organization_id', 'key'], unique=False)
    op.create_index('idx_org_settings_org_namespace', 'organization_settings', ['organization_id', 'namespace'], unique=False)
    op.add_column('organizations', sa.Column('theme_color', sa.String(length=7), nullable=True, comment='Primary brand color (hex e.g. #6d28d9)'))
    op.add_column('organizations', sa.Column('language', sa.String(length=20), server_default='en', nullable=False, comment='Default language for the organization'))
    op.add_column('organizations', sa.Column('default_ai_provider', sa.String(length=50), nullable=True, comment='Default AI provider (openai | anthropic | groq | gemini)'))
    op.add_column('organizations', sa.Column('default_image_provider', sa.String(length=50), nullable=True, comment='Default image generation provider'))
    op.add_column('organizations', sa.Column('default_ai_model', sa.String(length=100), nullable=True, comment='Default AI model identifier'))
    op.add_column('organizations', sa.Column('archived_at_ts', sa.DateTime(), nullable=True, comment='Soft-archived timestamp (org hidden from switcher but not deleted)'))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name of the organization',
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-safe unique identifier (immutable after creation)',
               existing_nullable=False)
    op.create_index('idx_pwd_reset_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('idx_pwd_reset_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('idx_payment_methods_org_id', 'payment_methods', ['organization_id'], unique=False)
    op.create_index('idx_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('idx_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('idx_payments_org_id', 'payments', ['organization_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_pii_scans_org', 'pii_scan_results', ['organization_id'], unique=False)
    op.create_index('idx_pipelines_org', 'pipelines', ['organization_id'], unique=False)
    op.create_index('idx_plan_features_plan_id', 'plan_features', ['plan_id'], unique=False)
    op.create_index('idx_announcements_range', 'platform_announcements', ['starts_at', 'ends_at'], unique=False)
    op.create_index('idx_platform_events_aggregate', 'platform_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('idx_platform_events_created_at', 'platform_events', ['created_at'], unique=False)
    op.create_index('idx_platform_events_event_type', 'platform_events', ['event_type'], unique=False)
    op.create_index('idx_platform_events_idempotency', 'platform_events', ['idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_index('idx_platform_events_org_id', 'platform_events', ['organization_id'], unique=False)
    op.create_index('idx_promo_redemptions_org_id', 'promo_code_redemptions', ['organization_id'], unique=False)
    op.create_index('idx_promo_redemptions_promo_id', 'promo_code_redemptions', ['promo_code_id'], unique=False)
    op.create_index('idx_promo_codes_code', 'promo_codes', ['code'], unique=False)
    op.create_index('idx_promo_codes_expires_at', 'promo_codes', ['expires_at'], unique=False)
    op.create_index('idx_prompt_ab_test_res_created', 'prompt_ab_test_results', ['created_at'], unique=False)
    op.create_index('idx_prompt_ab_test_res_test_var', 'prompt_ab_test_results', ['ab_test_id', 'variant'], unique=False)
    op.create_index('idx_prompt_ab_tests_org_status', 'prompt_ab_tests', ['organization_id', 'status'], unique=False)
    op.create_index('idx_prompt_ab_tests_prompt_a', 'prompt_ab_tests', ['prompt_a_id'], unique=False)
    op.create_index('idx_prompt_ab_tests_prompt_b', 'prompt_ab_tests', ['prompt_b_id'], unique=False)
    op.drop_constraint(op.f('prompt_analytics_prompt_id_key'), 'prompt_analytics', type_='unique')
    op.drop_index(op.f('ix_prompt_analytics_prompt_id'), table_name='prompt_analytics')
    op.create_index(op.f('ix_prompt_analytics_prompt_id'), 'prompt_analytics', ['prompt_id'], unique=True)
    op.add_column('prompt_collections', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompt_collections', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('prompt_collections', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_index(op.f('ix_prompt_collections_org_id'), table_name='prompt_collections')
    op.add_column('prompt_comments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompt_comments', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('prompt_comments', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('prompt_evaluations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompt_evaluations', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('prompt_evaluations', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('prompt_executions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompt_executions', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('prompt_executions', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_index(op.f('ix_prompt_executions_org_id'), table_name='prompt_executions')
    op.add_column('prompt_folders', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompt_folders', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('prompt_folders', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_index(op.f('ix_prompt_folders_org_id'), table_name='prompt_folders')
    op.drop_constraint(op.f('prompt_shares_share_token_key'), 'prompt_shares', type_='unique')
    op.add_column('prompt_test_cases', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompt_test_cases', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('prompt_test_cases', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('prompt_variables', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_unique_constraint('uq_prompt_version_num', 'prompt_versions', ['prompt_id', 'version_number'])
    op.create_foreign_key(None, 'prompt_versions', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_prompts_org_id_name'), table_name='prompts')
    op.create_index('idx_rate_limit_overrides_org', 'rate_limit_overrides', ['organization_id'], unique=False)
    op.alter_column('refresh_tokens', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='SHA-256 of the raw token — plaintext NEVER stored')
    op.alter_column('refresh_tokens', 'family_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Shared across all rotations — used for compromise detection')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               comment='TRUE = revoked due to security event (e.g. family compromise)',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Role name e.g. OWNER, ADMIN, CUSTOM_ANALYST',
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               comment='Role purpose and access level',
               existing_nullable=True)
    op.create_index('idx_security_alerts_org', 'security_alerts', ['organization_id'], unique=False)
    op.create_index('idx_sec_event_log_org', 'security_event_log', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_sec_event_log_user', 'security_event_log', ['user_id'], unique=False)
    op.create_index('idx_sec_incidents_org', 'security_incidents', ['organization_id'], unique=False)
    op.create_index('idx_sec_incidents_status', 'security_incidents', ['status'], unique=False)
    op.create_index('idx_subscriptions_org_id', 'subscriptions', ['organization_id'], unique=False)
    op.create_index('idx_subscriptions_period_end', 'subscriptions', ['current_period_end'], unique=False)
    op.create_index('idx_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_trial_ends', 'subscriptions', ['trial_ends_at'], unique=False)
    op.create_index('uq_subscriptions_org_active', 'subscriptions', ['organization_id'], unique=True, postgresql_where="status IN ('TRIAL','ACTIVE','PAST_DUE')")
    op.create_index('idx_ticket_msgs_ticket', 'support_ticket_messages', ['ticket_id'], unique=False)
    op.create_index('idx_support_tickets_org', 'support_tickets', ['organization_id'], unique=False)
    op.create_index('idx_support_tickets_status', 'support_tickets', ['status'], unique=False)
    op.create_index('idx_health_snapshots_time', 'system_health_snapshots', ['created_at'], unique=False)
    op.create_index('idx_threat_detect_org', 'threat_detections', ['organization_id'], unique=False)
    op.create_index('idx_threat_detect_status', 'threat_detections', ['status'], unique=False)
    op.create_index('idx_usage_records_metric', 'usage_records', ['metric_key'], unique=False)
    op.create_index('idx_usage_records_org_created', 'usage_records', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_usage_records_subscription', 'usage_records', ['subscription_id'], unique=False)
    op.add_column('user_organizations', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True, comment='Last time user was active in this organization'))
    op.add_column('user_organizations', sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='active | suspended | pending'))
    safe_alter_column_to_enum(
        'user_organizations', 'role', 'user_role_enum',
        sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='user_role_enum'),
        default_val=None, nullable=False
    )
    op.drop_constraint(op.f('uq_user_organizations_user_org'), 'user_organizations', type_='unique')
    op.create_index('idx_user_roles_org_id', 'user_roles', ['organization_id'], unique=False)
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_roles_user_org', 'user_roles', ['user_id', 'organization_id'], unique=False)
    op.create_index('idx_user_sessions_active', 'user_sessions', ['user_id', 'is_revoked', 'expires_at'], unique=False, postgresql_where='is_revoked = FALSE')
    op.create_index('idx_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_org_id', 'user_sessions', ['organization_id'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True, comment='When user requested account deletion'))
    op.add_column('users', sa.Column('scheduled_deletion_at', sa.DateTime(timezone=True), nullable=True, comment='Permanent deletion scheduled for this time (requested_at + 7 days)'))
    op.add_column('users', sa.Column('deletion_reason', sa.String(length=500), nullable=True, comment='Optional reason provided by user'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Primary identity — globally unique across platform',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash; NULL for SSO/OAuth-only accounts',
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='FALSE = deactivated account',
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='Platform superadmin — bypasses all org-level checks',
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='Email verified flag',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='UI preferences (theme, language, notification settings)',
               existing_nullable=True)
    op.create_index('idx_webhook_deliveries_endpoint', 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index('idx_webhook_deliveries_org', 'webhook_deliveries', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_webhook_endpoints_org', 'webhook_endpoints', ['organization_id'], unique=False)
    op.create_index('idx_webhook_events_org', 'webhook_events', ['organization_id'], unique=False)
    op.create_index('idx_webhook_events_status', 'webhook_events', ['status'], unique=False)
    safe_alter_column_to_enum(
        'workflow_definitions', 'status', 'workflowstatus',
        sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='workflowstatus'),
        default_val='DRAFT', nullable=False
    )
    safe_alter_column_to_enum(
        'workflow_definitions', 'trigger', 'workflowtrigger',
        sa.Enum('MANUAL', 'SCHEDULED', 'WEBHOOK', 'CAMPAIGN_EVENT', 'CRM_EVENT', name='workflowtrigger'),
        default_val='MANUAL', nullable=False
    )
    safe_alter_column_to_enum(
        'workflow_executions', 'status', 'executionstatus',
        sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'WAITING', name='executionstatus'),
        default_val='PENDING', nullable=False
    )
    op.create_index('idx_wf_schedules_next_run', 'workflow_schedules', ['next_run_at'], unique=False)
    op.create_index('idx_wf_schedules_workflow', 'workflow_schedules', ['workflow_id'], unique=False)
    safe_alter_column_to_enum(
        'workflow_steps', 'status', 'executionstatus',
        sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'WAITING', name='executionstatus'),
        default_val='PENDING', nullable=False
    )
    op.create_index('idx_wf_triggers_org', 'workflow_triggers', ['organization_id'], unique=False)
    op.create_index('idx_wf_triggers_workflow', 'workflow_triggers', ['workflow_id'], unique=False)
    op.create_index('idx_workflow_ver_workflow', 'workflow_versions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_ver_workflow', table_name='workflow_versions')
    op.drop_index('idx_wf_triggers_workflow', table_name='workflow_triggers')
    op.drop_index('idx_wf_triggers_org', table_name='workflow_triggers')
    op.alter_column('workflow_steps', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'WAITING', name='executionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_index('idx_wf_schedules_workflow', table_name='workflow_schedules')
    op.drop_index('idx_wf_schedules_next_run', table_name='workflow_schedules')
    op.alter_column('workflow_executions', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'WAITING', name='executionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('workflow_definitions', 'trigger',
               existing_type=sa.Enum('MANUAL', 'SCHEDULED', 'WEBHOOK', 'CAMPAIGN_EVENT', 'CRM_EVENT', name='workflowtrigger'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.alter_column('workflow_definitions', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='workflowstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.drop_index('idx_webhook_events_status', table_name='webhook_events')
    op.drop_index('idx_webhook_events_org', table_name='webhook_events')
    op.drop_index('idx_webhook_endpoints_org', table_name='webhook_endpoints')
    op.drop_index('idx_webhook_deliveries_org', table_name='webhook_deliveries')
    op.drop_index('idx_webhook_deliveries_endpoint', table_name='webhook_deliveries')
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='UI preferences (theme, language, notification settings)',
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Email verified flag',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Platform superadmin — bypasses all org-level checks',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='FALSE = deactivated account',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hash; NULL for SSO/OAuth-only accounts',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Primary identity — globally unique across platform',
               existing_nullable=False)
    op.drop_column('users', 'deletion_reason')
    op.drop_column('users', 'scheduled_deletion_at')
    op.drop_column('users', 'deletion_requested_at')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_org_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires_at', table_name='user_sessions')
    op.drop_index('idx_user_sessions_active', table_name='user_sessions', postgresql_where='is_revoked = FALSE')
    op.drop_index('idx_user_roles_user_org', table_name='user_roles')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_index('idx_user_roles_org_id', table_name='user_roles')
    op.create_unique_constraint(op.f('uq_user_organizations_user_org'), 'user_organizations', ['user_id', 'organization_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_organizations', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='user_role_enum'),
               type_=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='userrole'),
               existing_nullable=False)
    op.drop_column('user_organizations', 'status')
    op.drop_column('user_organizations', 'last_active_at')
    op.drop_index('idx_usage_records_subscription', table_name='usage_records')
    op.drop_index('idx_usage_records_org_created', table_name='usage_records')
    op.drop_index('idx_usage_records_metric', table_name='usage_records')
    op.drop_index('idx_threat_detect_status', table_name='threat_detections')
    op.drop_index('idx_threat_detect_org', table_name='threat_detections')
    op.drop_index('idx_health_snapshots_time', table_name='system_health_snapshots')
    op.drop_index('idx_support_tickets_status', table_name='support_tickets')
    op.drop_index('idx_support_tickets_org', table_name='support_tickets')
    op.drop_index('idx_ticket_msgs_ticket', table_name='support_ticket_messages')
    op.drop_index('uq_subscriptions_org_active', table_name='subscriptions', postgresql_where="status IN ('TRIAL','ACTIVE','PAST_DUE')")
    op.drop_index('idx_subscriptions_trial_ends', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_period_end', table_name='subscriptions')
    op.drop_index('idx_subscriptions_org_id', table_name='subscriptions')
    op.drop_index('idx_sec_incidents_status', table_name='security_incidents')
    op.drop_index('idx_sec_incidents_org', table_name='security_incidents')
    op.drop_index('idx_sec_event_log_user', table_name='security_event_log')
    op.drop_index('idx_sec_event_log_org', table_name='security_event_log')
    op.drop_index('idx_security_alerts_org', table_name='security_alerts')
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Role purpose and access level',
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Role name e.g. OWNER, ADMIN, CUSTOM_ANALYST',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE = revoked due to security event (e.g. family compromise)',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'family_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Shared across all rotations — used for compromise detection')
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='SHA-256 of the raw token — plaintext NEVER stored')
    op.alter_column('refresh_tokens', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_rate_limit_overrides_org', table_name='rate_limit_overrides')
    op.create_index(op.f('ix_prompts_org_id_name'), 'prompts', ['organization_id', 'name'], unique=False)
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.drop_constraint('uq_prompt_version_num', 'prompt_versions', type_='unique')
    op.drop_column('prompt_variables', 'version')
    op.drop_column('prompt_test_cases', 'updated_by')
    op.drop_column('prompt_test_cases', 'created_by')
    op.drop_column('prompt_test_cases', 'deleted_at')
    op.create_unique_constraint(op.f('prompt_shares_share_token_key'), 'prompt_shares', ['share_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_prompt_folders_org_id'), 'prompt_folders', ['organization_id'], unique=False)
    op.drop_column('prompt_folders', 'updated_by')
    op.drop_column('prompt_folders', 'created_by')
    op.drop_column('prompt_folders', 'deleted_at')
    op.create_index(op.f('ix_prompt_executions_org_id'), 'prompt_executions', ['organization_id'], unique=False)
    op.drop_column('prompt_executions', 'updated_by')
    op.drop_column('prompt_executions', 'created_by')
    op.drop_column('prompt_executions', 'deleted_at')
    op.drop_column('prompt_evaluations', 'updated_by')
    op.drop_column('prompt_evaluations', 'created_by')
    op.drop_column('prompt_evaluations', 'deleted_at')
    op.drop_column('prompt_comments', 'updated_by')
    op.drop_column('prompt_comments', 'created_by')
    op.drop_column('prompt_comments', 'deleted_at')
    op.create_index(op.f('ix_prompt_collections_org_id'), 'prompt_collections', ['organization_id'], unique=False)
    op.drop_column('prompt_collections', 'updated_by')
    op.drop_column('prompt_collections', 'created_by')
    op.drop_column('prompt_collections', 'deleted_at')
    op.drop_index(op.f('ix_prompt_analytics_prompt_id'), table_name='prompt_analytics')
    op.create_index(op.f('ix_prompt_analytics_prompt_id'), 'prompt_analytics', ['prompt_id'], unique=False)
    op.create_unique_constraint(op.f('prompt_analytics_prompt_id_key'), 'prompt_analytics', ['prompt_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_prompt_ab_tests_prompt_b', table_name='prompt_ab_tests')
    op.drop_index('idx_prompt_ab_tests_prompt_a', table_name='prompt_ab_tests')
    op.drop_index('idx_prompt_ab_tests_org_status', table_name='prompt_ab_tests')
    op.drop_index('idx_prompt_ab_test_res_test_var', table_name='prompt_ab_test_results')
    op.drop_index('idx_prompt_ab_test_res_created', table_name='prompt_ab_test_results')
    op.drop_index('idx_promo_codes_expires_at', table_name='promo_codes')
    op.drop_index('idx_promo_codes_code', table_name='promo_codes')
    op.drop_index('idx_promo_redemptions_promo_id', table_name='promo_code_redemptions')
    op.drop_index('idx_promo_redemptions_org_id', table_name='promo_code_redemptions')
    op.drop_index('idx_platform_events_org_id', table_name='platform_events')
    op.drop_index('idx_platform_events_idempotency', table_name='platform_events', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index('idx_platform_events_event_type', table_name='platform_events')
    op.drop_index('idx_platform_events_created_at', table_name='platform_events')
    op.drop_index('idx_platform_events_aggregate', table_name='platform_events')
    op.drop_index('idx_announcements_range', table_name='platform_announcements')
    op.drop_index('idx_plan_features_plan_id', table_name='plan_features')
    op.drop_index('idx_pipelines_org', table_name='pipelines')
    op.drop_index('idx_pii_scans_org', table_name='pii_scan_results')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_org_id', table_name='payments')
    op.drop_index('idx_payments_invoice_id', table_name='payments')
    op.drop_index('idx_payments_created_at', table_name='payments')
    op.drop_index('idx_payment_methods_org_id', table_name='payment_methods')
    op.drop_index('idx_pwd_reset_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_pwd_reset_expires_at', table_name='password_reset_tokens')
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='URL-safe unique identifier (immutable after creation)',
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name of the organization',
               existing_nullable=False)
    op.drop_column('organizations', 'archived_at_ts')
    op.drop_column('organizations', 'default_ai_model')
    op.drop_column('organizations', 'default_image_provider')
    op.drop_column('organizations', 'default_ai_provider')
    op.drop_column('organizations', 'language')
    op.drop_column('organizations', 'theme_color')
    op.drop_index('idx_org_settings_org_namespace', table_name='organization_settings')
    op.drop_index('idx_org_settings_org_key', table_name='organization_settings')
    op.drop_constraint(None, 'organization_invitations', type_='foreignkey')
    op.alter_column('organization_invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Invitation expires at this time (default: 72h from creation)',
               existing_nullable=False)
    op.alter_column('organization_invitations', 'token',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Secure random token (128-bit entropy, URL-safe base64)',
               existing_nullable=False)
    op.alter_column('organization_invitations', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='user_role_enum'),
               type_=postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'GUEST', name='userrole'),
               comment=None,
               existing_comment='Role to assign upon acceptance',
               existing_nullable=False)
    op.alter_column('organization_invitations', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Invitee email address',
               existing_nullable=False)
    op.drop_column('organization_invitations', 'revoked_at')
    op.drop_column('organization_invitations', 'revoked_by')
    op.drop_column('organization_invitations', 'last_resent_at')
    op.drop_column('organization_invitations', 'resent_count')
    op.drop_index('idx_oauth_providers_provider', table_name='oauth_providers')
    op.drop_index('idx_oauth_providers_org_id', table_name='oauth_providers')
    op.drop_index('idx_oauth_accounts_user_id', table_name='oauth_accounts')
    op.drop_index('idx_oauth_accounts_provider', table_name='oauth_accounts')
    op.alter_column('notifications', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('notifications', 'channel',
               existing_type=sa.Enum('IN_APP', 'EMAIL', 'SLACK', 'WEBHOOK', name='notificationchannel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'IN_APP'::character varying"))
    op.drop_index('idx_notification_templates_org', table_name='notification_templates')
    op.alter_column('notification_preferences', 'channel',
               existing_type=sa.Enum('IN_APP', 'EMAIL', 'SLACK', 'WEBHOOK', name='notificationchannel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('idx_notification_digests_user', table_name='notification_digests')
    op.drop_index('idx_notification_deliv_user', table_name='notification_deliveries')
    op.drop_index('idx_notification_deliv_org', table_name='notification_deliveries')
    op.drop_index('idx_notification_batches_org', table_name='notification_batches')
    op.drop_index('idx_maintenance_windows_start', table_name='maintenance_windows')
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.drop_index('idx_knowledge_retrieval_user', table_name='knowledge_retrieval_logs')
    op.drop_index('idx_knowledge_retrieval_org', table_name='knowledge_retrieval_logs')
    op.drop_index('idx_ip_allowlists_org', table_name='ip_allowlists')
    op.drop_index('idx_invoices_subscription_id', table_name='invoices')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_org_id', table_name='invoices')
    op.drop_index('idx_invoices_due_date', table_name='invoices')
    op.drop_index('idx_invoices_created_at', table_name='invoices')
    op.drop_index('idx_invoice_line_items_invoice_id', table_name='invoice_line_items')
    op.alter_column('integrations', 'status',
               existing_type=sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'PENDING_AUTH', name='integrationstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING_AUTH'::character varying"))
    op.alter_column('integrations', 'provider',
               existing_type=sa.Enum('SLACK', 'GOOGLE_DRIVE', 'GMAIL', 'GOOGLE_CALENDAR', 'HUBSPOT', 'SALESFORCE', 'WEBHOOK', 'CUSTOM_API', name='integrationprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('idx_sync_logs_org', table_name='integration_sync_logs')
    op.drop_index('idx_impersonation_logs_user', table_name='impersonation_logs')
    op.drop_index('idx_impersonation_logs_admin', table_name='impersonation_logs')
    op.drop_index('idx_email_subs_org_email', table_name='email_subscriptions')
    op.drop_index('idx_email_sends_status', table_name='email_sends')
    op.drop_index('idx_email_sends_org_camp', table_name='email_sends')
    op.drop_index('idx_email_sends_contact', table_name='email_sends')
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.drop_index('idx_embeddings_org_model', table_name='document_chunk_embeddings')
    op.drop_index('idx_embeddings_chunk_id', table_name='document_chunk_embeddings')
    op.drop_index('idx_deals_pipeline_stage', table_name='deals')
    op.drop_index('idx_deals_owner', table_name='deals')
    op.drop_index('idx_deals_org', table_name='deals')
    op.drop_index('idx_deals_contact', table_name='deals')
    op.drop_index('idx_deals_company', table_name='deals')
    op.drop_index('idx_deal_stages_pipeline', table_name='deal_stages')
    op.drop_index('idx_classification_rules_org', table_name='data_classification_rules')
    op.drop_index('idx_credit_tx_type', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_reference', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_org_created', table_name='credit_transactions')
    op.drop_index('ix_conversation_memories_org_id', table_name='conversation_memories')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.drop_index('idx_custom_values_contact', table_name='contact_custom_values')
    op.drop_index('idx_custom_fields_org', table_name='contact_custom_fields')
    op.drop_index('idx_assessments_org', table_name='compliance_assessments')
    op.create_index(op.f('ix_companies_organization_id'), 'companies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.drop_index('idx_campaign_events_type', table_name='campaign_events')
    op.drop_index('idx_campaign_events_org_camp', table_name='campaign_events')
    op.drop_index('idx_campaign_events_created', table_name='campaign_events')
    op.drop_index('idx_campaign_events_contact', table_name='campaign_events')
    op.drop_index('idx_campaign_audiences_type', table_name='campaign_audiences')
    op.drop_index('idx_campaign_audiences_org', table_name='campaign_audiences')
    op.drop_index('idx_billing_plans_tier', table_name='billing_plans')
    op.drop_index('idx_billing_plans_is_active', table_name='billing_plans', postgresql_where='is_active = TRUE')
    op.drop_index('idx_billing_alerts_org_id', table_name='billing_alerts')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='CREATED | UPDATED | DELETED | ACCESSED | EXPORTED | RESTORED | PURGED',
               existing_nullable=False)
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.drop_index('idx_api_keys_org_id', table_name='api_keys')
    op.drop_index('idx_api_keys_active', table_name='api_keys', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_analytics_widgets_dash', table_name='analytics_widgets')
    op.drop_index('idx_snapshots_org_metric_period', table_name='analytics_snapshots')
    op.drop_index('idx_snapshots_module', table_name='analytics_snapshots')
    op.drop_index('idx_analytics_reports_org', table_name='analytics_reports')
    op.drop_index('idx_report_runs_report', table_name='analytics_report_runs')
    op.drop_index('idx_report_runs_org', table_name='analytics_report_runs')
    op.drop_index('idx_funnels_org', table_name='analytics_funnels')
    op.drop_index('idx_funnel_steps_funnel', table_name='analytics_funnel_steps')
    op.drop_index('idx_analytics_events_org_type', table_name='analytics_events')
    op.drop_index('idx_analytics_dashboards_org', table_name='analytics_dashboards')
    op.drop_index('idx_cohorts_org', table_name='analytics_cohorts')
    op.create_index(op.f('ix_ai_token_usages_user_id'), 'ai_token_usages', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_token_usages_organization_id'), 'ai_token_usages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_token_usages_created_at'), 'ai_token_usages', ['created_at'], unique=False)
    op.drop_column('ai_token_usages', 'request_id')
    op.drop_column('ai_token_usages', 'agent')
    op.drop_column('ai_token_usages', 'capability')
    op.drop_column('ai_token_usages', 'retry_count')
    op.drop_column('ai_providers', 'config')
    op.drop_column('ai_models', 'supports_images')
    op.create_index(op.f('ix_image_library_user_id'), 'ai_image_library', ['user_id'], unique=False)
    op.create_index(op.f('ix_image_library_run_id'), 'ai_image_library', ['run_id'], unique=False)
    op.create_index(op.f('ix_image_library_parent_id'), 'ai_image_library', ['parent_id'], unique=False)
    op.create_index(op.f('ix_image_library_org_id'), 'ai_image_library', ['organization_id'], unique=False)
    op.create_index(op.f('ix_image_library_created_at'), 'ai_image_library', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_library_campaign_id'), 'ai_image_library', ['campaign_id'], unique=False)
    op.drop_column('ai_image_collections', 'version')
    op.drop_column('ai_image_collections', 'updated_by')
    op.drop_column('ai_image_collections', 'created_by')
    op.drop_column('ai_image_collections', 'deleted_at')
    op.drop_column('ai_image_collections', 'updated_at')
    op.drop_index('idx_agent_tools_type', table_name='agent_tools')
    op.drop_index('idx_agent_tools_org', table_name='agent_tools')
    op.drop_index('idx_agent_tool_exec_run', table_name='agent_tool_executions')
    op.drop_index('idx_agent_tool_exec_org', table_name='agent_tool_executions')
    op.alter_column('agent_runs', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agentrunstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('agent_memories', 'memory_type',
               existing_type=sa.Enum('SHORT_TERM', 'LONG_TERM', 'EPISODIC', 'SEMANTIC', name='memorytype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'SHORT_TERM'::character varying"))
    op.drop_index('idx_agent_kb_collection', table_name='agent_knowledge_bindings')
    op.drop_index('idx_agent_kb_agent', table_name='agent_knowledge_bindings')
    op.alter_column('agent_evaluations', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('agent_definitions', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='agentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('agent_definitions', 'agent_type',
               existing_type=sa.Enum('MARKETING', 'CONTENT', 'CAMPAIGN', 'CRM', 'ANALYTICS', 'RESEARCH', 'SEO', 'WORKFLOW', 'CUSTOM', 'SALES', 'SUPPORT', 'IMAGE', 'SOCIAL', name='agenttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'CUSTOM'::character varying"))
    op.drop_index('idx_agent_analytics_org', table_name='agent_analytics')
    op.drop_index('idx_admin_action_logs_user', table_name='admin_action_logs')
    op.drop_index('idx_email_verification_user_id', table_name='email_verification_tokens')
    op.drop_index('idx_email_verification_expires_at', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
